### ISSUE TITLE
UnorderedFoldable and UnorderedTraverse appear twice

### ISSUE THREAD

**Issue by jiftechnify** [tpolecat/cats-infographic#17]
1.
![uof1](https://user-images.githubusercontent.com/12131273/35881311-c51c81ac-0bc3-11e8-9890-cf089da6c2e7.png)

2.
![uof2](https://user-images.githubusercontent.com/12131273/35881391-fd52b9f6-0bc3-11e8-8673-f5d5277bcb00.png)

They appear 
1. above Foldable/Traverse (on the left-top of the major typeclass hierarchy)
2. on the right of NonEmptyParallel/Parallel (separated from the major hierarchy)

I think the latter should be removed.

**Comment by tpolecat** [comment]
Doh! Thanks!
